# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

directories %w{config lib priv test web}

ENV["IN_GUARD"] = "true"

guard :elixir do
  watch(%r{^test/(.*)_test\.exs$})
  watch(%r{^lib/(.+)\.ex$})           { "test" }
  watch(%r{^test/test_helper.exs$})   { "test" }

  watch(%r{^web/models/(.+)\.ex$}) { |m| "test/models/#{m[1]}_test.exs" }

  watch(%r{^web/controllers/(.+)\.ex$}) do |m|
    "test/controllers/#{m[1]}_test.exs"
  end

  watch(%r{^web/controllers/.+upload_controller\.ex$}) do |m|
    "test/controllers/upload_controller"
  end

  watch(%r{^web/controllers/download_controller\.ex$}) do |m|
    "test/controllers/download_controller"
  end

  watch(%r{^web/controllers/feedback_controller\.ex$}) do |m|
    "test/controllers/feedback_controller"
  end
end
